version: '1'
services:
  app:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: mongo
    ports:
      - "3307:3307"